### PR TITLE
Current sensor statistics: to polar to decomposed statistics

### LINKED ISSUE #1068: [BUG] Handle current sensor for i_measured=0 and i_angle_measured=npi/2
**Describe the bug**

In #1056 we mention that the current sensor is invalid for this specific case of measured value. This issue is to handle such a case. Although unrealistic, it is more neat to support the whole range.

@mgovers suggested a nice idea to to extend the 1st order approximation of polar -> rectangular variance to 2nd order order approximation to cover this gap.

### PR DESCRIPTION
**Pull request by mgovers**
Fixes #1068

### CODE REVIEW

File: tests/cpp_unit_tests/test_statistics.cpp [hunk 1]
```diff
@@ -444,11 +452,34 @@ TEST_CASE("Test statistics") {
 
                     CHECK(decomposed.real_component.value == doctest::Approx(real(uniform.value)));
                     CHECK(decomposed.imag_component.value == doctest::Approx(imag(uniform.value)));
-                    CHECK(decomposed.real_component.variance == doctest::Approx(uniform.variance / 2));
+                    // the following terms break the symmetry between
+                    // - polar -> decomposed -> uniform
+                    // - polar -> independent -> uniform
+                    // note that that is OK because decomposed is a 2D transformation of polar, while
+                    // independent is a radial-only transformation of polar, so it is more stable.
```
Comment (mgovers) [inline tests/cpp_unit_tests/test_statistics.cpp:459]: This also means that because we use `DecomposedComplexRandomVariable` in our `CurrentSensorCalcParams`, our `IterativeLinear` solver actually uses a slightly larger variance than strictly necessary (because it uses `UniformComplexRandomVariable`, not `DecomposedComplexRandomVariable`).

This can be resolved by using `PolarComplexRandomVariable` in our `CurrentSensorCalcParams` and deferring the conversion either to `DecomposedComplexRandomVariable` (NRSE) or directly to `UniformComplexRandomVariable` (ILSE) where needed. `MeasuredValues` may then require some updates as well, as it would require different accumulations for the ILSE and the NRSE.

Out of scope of this PR, though.

File: power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp [hunk 2]
```diff
@@ -126,6 +126,27 @@ template <symmetry_tag sym_type> struct DecomposedComplexRandVar {
...
+namespace detail {
+inline auto compute_decomposed_variance_from_polar(auto const& magnitude, auto const& cos_angle, auto const& sin_angle,
+                                                   auto const& magnitude_variance, auto const& angle_variance) {
+    auto const cos2_angle = cos_angle * cos_angle;
+    auto const sin2_angle = sin_angle * sin_angle;
+    auto const magnitude2 = magnitude * magnitude;
+
+    // // first order approximation
+    // return std::make_pair(magnitude_variance * cos2_angle + magnitude2 * angle_variance * sin2_angle,
+    //                       magnitude_variance * sin2_angle + magnitude2 * angle_variance * cos2_angle);
```
Comment (mgovers) [inline power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: do we want to remove this?

File: power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp [hunk 3]
```diff
@@ -145,65 +166,66 @@ template <symmetry_tag sym_type> struct PolarComplexRandVar {
     }
 
     // For sym to sym conversion:
-    // Var(I_Re) ≈ Var(I) * cos^2(θ) + Var(θ) * I^2 * sin^2(θ)
-    // Var(I_Im) ≈ Var(I) * sin^2(θ) + Var(θ) * I^2 * cos^2(θ)
+    // Var(I_Re) ≈ Var(I) * cos^2(θ) + Var(θ) * I^2 * sin^2(θ)                    // first order
+    //             + 1/2 * Var(θ)^2 * I^2 * sin^2(θ) + Var(I) * Var(θ) * cos^2(θ) // second order
+    // Var(I_Im) ≈ Var(I) * sin^2(θ) + Var(θ) * I^2 * cos^2(θ)                    // first order
+    //             + 1/2 * Var(θ)^2 * I^2 * cos^2(θ) + Var(I) * Var(θ) * sin^2(θ) // second order
```
Comment (mgovers) [inline power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]:
```suggestion
    //             + 1/2 * Var(θ)^2 * I^2 * cos^2(θ) + Var(I) * Var(θ) * sin^2(θ) // second order
    // Var(I_Im) ≈ Var(I) * sin^2(θ) + Var(θ) * I^2 * cos^2(θ)                    // first order
    //             + 1/2 * Var(θ)^2 * I^2 * sin^2(θ) + Var(I) * Var(θ) * cos^2(θ) // second order
```

File: power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp [hunk 4]
```diff
@@ -126,6 +126,27 @@ template <symmetry_tag sym_type> struct DecomposedComplexRandVar {
     }
 };
 
+namespace detail {
+inline auto compute_decomposed_variance_from_polar(auto const& magnitude, auto const& cos_angle, auto const& sin_angle,
```
Comment (mgovers) [inline power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp:148]: add docstring to explain how first order + second order are obtained

File: power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp [hunk 5]
```diff
@@ -126,6 +126,41 @@ template <symmetry_tag sym_type> struct DecomposedComplexRandVar {
...
+//              + 1/2 * \Sum_{jk} Var(x_j) * ||∂²f_i/∂x_j∂x_k||^2 Var(x_k) // second order
+//
+// Re{I} = I cos(θ)
+// Im{I} = I sin(θ)
+//
+// ∂Re{I}/∂I = cos(θ)            ∂Im{I}/∂I = sin(θ)
+// ∂Re{I}/∂θ = -I sin(θ)         ∂Im{I}/∂θ = I cos(θ)
+// ∂²Re{I}/∂I² = 0               ∂²Im{I}/∂I² = 0
+// ∂²Re{I}/∂θ² = -I cos(θ)       ∂²Im{I}/∂θ² = -I sin(θ)
+// ∂²Re{I}/∂I∂θ = -sin(θ)        ∂²Im{I}/∂I∂θ = cos(θ)
```
Comment (TonyXiang8787) [inline power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: @mgovers  I have removed the PR from merge queue to make sure we understand this. Are you using a non-ascii character here?

I have hesitation about this. To use non-ascii character in the code.

Comment (mgovers) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: i can rewrite to just use only `d` directly

Comment (TonyXiang8787) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: I think that's a good idea

Comment (TonyXiang8787) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: Also avoid the superscript square, that's not ascii either

Comment (mgovers) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: fixed + removed from history

Comment (TonyXiang8787) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: the superscript `²` should also be removed.

Comment (mgovers) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: that is ascii though (https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.ascii-code.com/character/%25C2%25B2&ved=2ahUKEwiU6YnVzKOQAxV2_7sIHeugCWAQFnoECBcQAQ&usg=AOvVaw0yd-yM2ve2Tjh05zJ2gPRr)

we also use it in other locations in our docs

Comment (TonyXiang8787) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: It's encoding is `178`, outside of ascii.

Comment (mgovers) [reply power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp]: done
